# Generated by Django 5.1.6 on 2025-02-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
