# Generated by Django 5.1.6 on 2025-02-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_rename_duration_minutes_assessment_duration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessment',
            table='assessment',
        ),
    ]
