# Generated by Django 5.1.6 on 2025-02-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_alter_assessment_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
