# Generated by Django 5.1.6 on 2025-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_assessment_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scheduled_reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
