# Generated by Django 5.1.6 on 2025-02-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homework_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='due_to',
            new_name='due_at',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='time_start',
            new_name='start_time',
        ),
    ]
