# Generated by Django 5.1.6 on 2025-04-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_rename_due_to_homework_due_at_and_more'),
        ('lesson', '0004_alter_lesson_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lesson_due',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='due_homework', to='lesson.lesson'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lesson_given',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_homework', to='lesson.lesson'),
        ),
    ]
