# Generated by Django 5.1.6 on 2025-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_alter_homework_lesson_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='scheduled_reminder_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
