# Generated by Django 5.1.6 on 2025-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_homework_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='scheduled_reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
