# Generated by Django 5.1.6 on 2025-04-19 17:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_length', models.DurationField(default=datetime.timedelta(seconds=5400))),
                ('recieve_lesson_remainders', models.BooleanField(default=False)),
                ('lesson_renainder_timing', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('recieve_assessment_remainders', models.BooleanField(default=True)),
                ('assessment_renainder_timing', models.DurationField(default=datetime.timedelta(days=3))),
                ('recieve_homework_remainders', models.BooleanField(default=True)),
                ('homework_renainder_timing', models.DurationField(default=datetime.timedelta(days=2))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
