# Generated by Django 5.1.6 on 2025-04-22 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lesson_length',
            new_name='assessment_duration',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lesson_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
    ]
