# Generated by Django 5.1.6 on 2025-04-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_lesson_length_userprofile_assessment_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='assessment_renainder_timing',
            new_name='assessment_renminder_timing',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='homework_renainder_timing',
            new_name='homework_remainder_timing',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lesson_renainder_timing',
            new_name='lesson_remainder_timing',
        ),
    ]
