# Generated by Django 5.1.6 on 2025-04-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_rename_assessment_renainder_timing_userprofile_assessment_renminder_timing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='assessment_renminder_timing',
            new_name='assessment_remainder_timing',
        ),
    ]
