# Generated by Django 5.1.6 on 2025-05-01 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_rename_assessment_renminder_timing_userprofile_assessment_remainder_timing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='userprofile',
        ),
    ]
