# Generated by Django 5.1.6 on 2025-07-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='remainders_type',
            field=models.CharField(choices=[('P', 'Push notifications'), ('E', 'Email remainders')], default='P', max_length=1),
        ),
    ]
