# Generated by Django 5.1.6 on 2025-07-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_userprofile_remainders_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='assessment_remainder_timing',
            new_name='assessment_reminder_timing',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='homework_remainder_timing',
            new_name='homework_reminder_timing',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lesson_remainder_timing',
            new_name='lesson_reminder_timing',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='recieve_assessment_remainders',
            new_name='recieve_assessment_reminders',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='recieve_homework_remainders',
            new_name='recieve_homework_reminders',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='recieve_lesson_remainders',
            new_name='recieve_lesson_reminders',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='remainders_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_type',
            field=models.CharField(choices=[('P', 'Push notifications'), ('E', 'Email notifications')], default='P', max_length=1),
        ),
    ]
