# Generated by Django 5.1.6 on 2025-07-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_rename_assessment_remainder_timing_userprofile_assessment_reminder_timing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reminder_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_method',
            field=models.CharField(choices=[('P', 'Push'), ('E', 'Email'), ('B', 'Both')], default='P', max_length=1),
        ),
    ]
