# Generated by Django 5.1.6 on 2025-07-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_remove_userprofile_reminder_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='recieve_assessment_reminders',
            new_name='receive_assessment_reminders',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='recieve_homework_reminders',
            new_name='receive_homework_reminders',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='recieve_lesson_reminders',
            new_name='receive_lesson_reminders',
        ),
    ]
