# Generated by Django 5.1.6 on 2025-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_rename_recieve_assessment_reminders_userprofile_receive_assessment_reminders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='time_display_format',
            field=models.CharField(choices=[('24', '24-hour (13:00)'), ('12', '12-hour (1:00 PM)')], default='24', max_length=2),
        ),
    ]
