# Generated by Django 5.1.6 on 2025-02-13 17:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('L', 'Lecture'), ('P', 'Practice'), ('S', 'Seminar'), ('Y', 'Self-Study')], max_length=1)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.DurationField(default=datetime.timedelta(seconds=5400))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
