# Generated by Django 5.1.6 on 2025-02-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.CharField(choices=[('L', 'Lecture'), ('P', 'Practice'), ('S', 'Seminar'), ('Y', 'Self-Study')], default='L', max_length=1),
        ),
    ]
