# Generated by Django 5.1.6 on 2025-02-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_lesson_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='duration_minutes',
            new_name='duration',
        ),
    ]
