# Generated by Django 5.1.6 on 2025-02-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_rename_duration_minutes_lesson_duration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lesson',
            table='lesson',
        ),
    ]
