# Generated by Django 5.1.6 on 2025-04-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_alter_lesson_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
