# Generated by Django 5.1.6 on 2025-07-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='scheduled_reminder_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
