# Generated by Django 5.1.6 on 2025-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_lesson_reminder_sent_lesson_scheduled_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='scheduled_reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
